-- Generated by nwg-displays on 2026-09-08 at 12:17:11. Do not edit manually.

hl.monitor({
    output = "desc:ASUSTek COMPUTER INC PA278CV N6LMQS220435",
    mode = "2560x1440@59.95",
    position = "2560x0",
    scale = 1.0,
    vrr = 0,
    transform = 5
})
hl.monitor({
    output = "desc:ASUSTek COMPUTER INC PA278CV N6LMQS220440",
    mode = "2560x1440@59.95",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
